# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/133EC_7mwsGw8s0Dh6SgCnLbP05iQhvcb
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile our_application.py
# import streamlit as st
# st.write("Hasini")

!wget -q -O - ipv4.icanhazip.com

! streamlit run our_application.py & npx localtunnel --port 8501